# 服务初始化的配置文件 执行代码详见 ./initialize/initialize.go
# This is the service initialization configuration file execution code see ./initialize/initialize.go
Mode: debug

Redis:
  Db: 0
  # 设置Addr开启redis
  Addr: ""
  Password: ""

System:
  Addr: 8080
  RouterPrefix: ""

Mysql:
  Path: "leap-ledger-mysql"
  Port: "3306"
  Config: "parseTime=True&loc=Local"
  DbName: "leap_ledger"
  Username: "root"
  Password: ""

Nats:
  ServerUrl: nats://127.0.0.1:4222
  Subjects: [createTourist,statisticUpdate,transactionSync]

Captcha:
  KeyLong: 6
  ImgWidth: 180
  ImgHeight: 50
  OpenCaptcha: 0
  OpenCaptchaTimeout: 3600
  EmailCaptcha: 0
  EmailCaptchaTimeOut: 3600

ThirdParty:
  # WeCom目前只用于发送邮件
  WeCom:
    # 设置CorpId和CorpSecret开启服务
    CorpId: ""
    CorpSecret: ""
  # ai服务暂时只有中文相似度比较，用于交易类型的匹配 基于[https://huggingface.co/google-bert/bert-base-chinese]简单实现
  Ai:
    # 设置Host和Port开启服务
    Host: "" # leap-ledger-ai-server
    Port: "" # 5000
    MinSimilarity: 0.85