redis:
  db: 0
  addr: 127.0.0.1:6379
  password: "123456"

system:
  env: public
  addr: 8080
  dbType: mysql
  routerPrefix: ""

mysql:
  path: "202.23.32.1"
  port: "3306"
  config: "parseTime=True"
  dbName: "keep_account"
  username: "root"
  password: "123456"
  logMode: ""

captcha:
  keyLong: 6
  imgWidth: 240
  imgHeight: 80
  openCaptcha: 0
  openCaptchaTimeout: 3600

