version: '3'
services:
  leap-ledger-server:
    container_name: leap-ledger-server
    image: registry.cn-hangzhou.aliyuncs.com/xiaozirun/leap-ledger:latest
    build:
      context: F:\GO_project\KeepAccount
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "4222:4222"
    environment:
      - CONFIG_FILE_NAME=production_config.yaml
    networks:
      - leap-ledger-network
#  leap-ledger-ai-server:
#    container_name: leap-ledger-ai-server
#    image: registry.cn-hangzhou.aliyuncs.com/xiaozirun/leap-ledger-ai:latest
#    build:
#      context: D:\development\project\github\test
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"
#    networks:
#      - leap-ledger-network

networks:
  leap-ledger-network:
