version: '4'
services:
  leap-ledger-server:
    container_name: leap-ledger-server
    image: registry.cn-hangzhou.aliyuncs.com/xiaozirun/leap-ledger:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE_NAME=production_config.yaml
    volumes:
      - ./log:/go/LeapLedger/log
    networks:
      - leap-ledger-network
    depends_on:
      - leap-ledger-mysql
  leap-ledger-mysql:
    container_name: leap-ledger-mysql
    image: mysql:8.0.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: leap_ledger
    ports:
      - "3306:3306"
    volumes:
      - ../LeapLedgerMysql/data:/var/lib/mysql
    networks:
      - leap-ledger-network
networks:
  leap-ledger-network: