name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  test-and-update-docs:
    uses: ./.github/workflows/common-test-and-update-docs.yml
    with:
      ref: ${{ github.ref }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
  push-image:
    needs: test-and-update-docs
    uses: ./.github/workflows/common-push-image.yml
    with:
      tag: latest
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}