name: Test And Update Docs

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  test-and-update-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t xiaozirun/leap-ledger:latest -f docker/Dockerfile .

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start server
        run: |
          docker-compose -f docker-compose.yaml up -d leap-ledger-mysql && docker-compose -f docker-compose.yaml up -d

      - name: Run tests and make report
        run: |
          docker exec leap-ledger-server sh -c "go install github.com/jstemmer/go-junit-report@latest"
          docker exec leap-ledger-server sh -c "go test -timeout 5m -v 2>&1 ./... -coverprofile=docs/coverage.out | go-junit-report > docs/test-report.xml"
        continue-on-error: false

      - name: Upload test-report.xml
        uses: actions/upload-artifact@v4
        with:
          name: test-report.xml
          path: docs/test-report.xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: docs/coverage.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: docs/test-report.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Execute updateDocs.sh in container
        run: docker exec leap-ledger-server sh "./docs/updateDocs.sh"

      - name: Commit and push changes
        # https://github.com/actions/checkout/discussions/479
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -u docs/docs.go docs/swagger.json docs/swagger.yaml
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "update docs" || echo "No changes to commit."
            git push origin ${{ inputs.ref }}
          fi
        continue-on-error: true

      - name: Docker Compose Down
        run: |
          docker-compose -f docker-compose.yaml down