name: update docs

on:
  workflow_dispatch:
  push:
    branches: [ "bug_account_v2" ]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/bug_account_v2'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"

      - name: Execute updateDocs.sh in container
        run: docker exec leap-ledger-server sh "./docs/updateDocs.sh"

      - name: Commit and push changes
        # https://github.com/actions/checkout/discussions/479
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update docs"
            git push origin ${{ github.ref }}
          fi

      - name: Docker Compose Down
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
          command: down
